### ISSUE TITLE
Resulting config json could be simplified after dump

### ISSUE THREAD

**Issue by ponchohoncho** [reillychase/Ubiquiti-USG-DHCP-Option-66#1]
Hi! Thanks for this great resource. I wanted to give you a quick heads up that the config you paste into config.gateway.json can (and probably should) be simplified from the config you get from the dump. Your example has a lot of extra config info that could cause confusion as it will overwrite what is set in the Unifi controller web UI. I was able to trim mine down to the following, for example

```
{
 "service": {
	"dhcp-server": {
		"shared-network-name": {
			"LAN_192.168.1.0-24": {
				"subnet": {
					"192.168.1.0/24": {
						"tftp-server-name": "http://url.of.config.srvr"
						}
					}
				}
			}
		}
	}
}
```

**Comment by ponchohoncho** [comment]
Since the config json you upload to the controller supplements the config you set on the controller's web UI, you don't want to clobber your web UI settings with json settings, in case you change things like DHCP ranges later.

**Comment by reillychase** [comment]
Thanks! Good idea, I will update it with your code

**Comment by reillychase** [comment]
Resolved
